/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.IT_Coffee.UI;

import Com.IT_Coffee.DAO.NhanVienDAO;
import Com.IT_Coffee.Entity.NhanVien;
import Com.IT_Coffee.utils.Auth;
import Com.IT_Coffee.utils.MsgBox;
import Com.IT_Coffee.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.examples.hsmf.Msg2txt;
import org.apache.poi.hwpf.usermodel.Table;

/**
 *
 * @author Dang
 */
public class NhanVienDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form NhanVienDiaLog
     */
    public NhanVienDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        panDemo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdoQuanLi = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        txtHoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        txtSDT = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        lblAnh = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnChonAnh = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnMucLuong = new javax.swing.JLabel();
        txtSoNgayLamViec = new javax.swing.JTextField();
        txtTienThuongThem = new javax.swing.JTextField();
        cboTienLuong = new javax.swing.JComboBox();
        txtTongTienLuong = new javax.swing.JTextField();
        btnTinhTien = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMK2 = new javax.swing.JPasswordField();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân Viên");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Nhân Viên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mật khẩu:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Họ Tên:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Giới Tính:");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(255, 255, 255));
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(255, 255, 255));
        rdoNu.setText("Nữ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vai Trò:");

        buttonGroup2.add(rdoQuanLi);
        rdoQuanLi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoQuanLi.setForeground(new java.awt.Color(255, 255, 255));
        rdoQuanLi.setText("Quản Lí");

        buttonGroup2.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        rdoNhanVien.setText("Nhân viên");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số Điện Thoại:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gmail:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lương:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Địa Chỉ:");

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtGmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblAnh.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblAnh.setForeground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(102, 102, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/them24.png"))); // NOI18N
        btnThem.setText("Thêm Nhân Viên");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(102, 102, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/sua24.png"))); // NOI18N
        btnSua.setText("Sửa Nhân Viên");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 102, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/xoa24.png"))); // NOI18N
        btnXoa.setText("Xóa Nhân Viên");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(102, 102, 255));
        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/moi24.png"))); // NOI18N
        btnLamMoi.setText("        Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnChonAnh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/mâynh.jpg"))); // NOI18N
        btnChonAnh.setText("Chọn Ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Số ngày làm việc:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tiền Thưởng Thêm:");

        btnMucLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMucLuong.setForeground(new java.awt.Color(255, 255, 255));
        btnMucLuong.setText("Mức Lương:");

        txtSoNgayLamViec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTienThuongThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cboTienLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboTienLuong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100000", "200000", "300000", "400000" }));

        txtTongTienLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnTinhTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/maytinhtay.jpg"))); // NOI18N
        btnTinhTien.setText("Tính Tiền Lương");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tổng Tiền Lương");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Xác Nhận Mật Khẩu:");

        txtMK2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnFirst.setBackground(new java.awt.Color(102, 102, 255));
        btnFirst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/first24.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(102, 102, 255));
        btnPrev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/prev24.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(102, 102, 255));
        btnLast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/last24.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(102, 102, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/next24.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDemoLayout = new javax.swing.GroupLayout(panDemo);
        panDemo.setLayout(panDemoLayout);
        panDemoLayout.setHorizontalGroup(
            panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDemoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDemoLayout.createSequentialGroup()
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panDemoLayout.createSequentialGroup()
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panDemoLayout.createSequentialGroup()
                                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rdoNam)
                                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMK2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rdoQuanLi))
                                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panDemoLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panDemoLayout.createSequentialGroup()
                            .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(208, 208, 208))
                        .addGroup(panDemoLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(133, 133, 133)
                            .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdoNhanVien)
                                .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panDemoLayout.createSequentialGroup()
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDemoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDemoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDemoLayout.createSequentialGroup()
                                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDemoLayout.createSequentialGroup()
                                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addGap(21, 21, 21)
                                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoNgayLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTienThuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDemoLayout.createSequentialGroup()
                                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnMucLuong)
                                            .addComponent(jLabel13))
                                        .addGap(21, 21, 21)
                                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTongTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTinhTien))))
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDemoLayout.createSequentialGroup()
                                .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))))))
        );
        panDemoLayout.setVerticalGroup(
            panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDemoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panDemoLayout.createSequentialGroup()
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtMK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDemoLayout.createSequentialGroup()
                                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panDemoLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(rdoNam)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDemoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoNu))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(panDemoLayout.createSequentialGroup()
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChonAnh)
                            .addComponent(rdoNhanVien)
                            .addComponent(rdoQuanLi)
                            .addComponent(jLabel7))
                        .addGap(58, 58, 58)))
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(txtSoNgayLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(24, 24, 24)
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi)
                    .addComponent(txtTienThuongThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(17, 17, 17)
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMucLuong))
                .addGap(20, 20, 20)
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnFirst)
                    .addComponent(btnLast))
                .addGap(18, 18, 18)
                .addGroup(panDemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhTien)
                    .addComponent(btnPrev)
                    .addComponent(btnNext))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        tabs.addTab("Nhân Viên", panDemo);

        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MaNV", "Tên Nhân Viên", "Giới Tính", "Vai Trò", "Địa Chỉ", "Số Điện Thoại", "Gmail", "Lương ", "Hình"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/Search.png"))); // NOI18N
        jLabel16.setText("Tìm Kiếm Nhân Viên Theo Tên:");

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1395, Short.MAX_VALUE)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Danh Sách", pan2);

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 790));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/backgroupNhanVien.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        this.tinhTien();
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        TinhTien();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        this.chonAnh();
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        this.timKiem();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblNhanVien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.Last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.First();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.Next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.Prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhanVienDiaLog dialog = new NhanVienDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLast;
    private javax.swing.JLabel btnMucLuong;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboTienLuong;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel panDemo;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLi;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JPasswordField txtMK2;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoNgayLamViec;
    private javax.swing.JTextField txtTienThuongThem;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongTienLuong;
    // End of variables declaration//GEN-END:variables

    NhanVienDAO dao = new NhanVienDAO();
    int row = -1;

    private void init() {
        this.setTitle("QUẢN LÝ NHÂN VIÊN");
        setLocationRelativeTo(null);
        panDemo.setBackground(new Color(0, 0, 0, 200));
        pan2.setBackground(new Color(0, 0, 0, 64));
        txtTongTienLuong.setEnabled(false);
        tblNhanVien.setDefaultEditor(Object.class, null);

        ImageIcon image = new ImageIcon("logos\\no-image-nv.png");
        Image im = image.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                lblAnh.getHeight(), im.SCALE_SMOOTH));
        lblAnh.setIcon(icon);

        fillTable();
        this.updateStatus();
        rdoQuanLi.setSelected(true);
        rdoNam.setSelected(true);
    }

    void TinhTien() {
        txtSoNgayLamViec.setText("");
        txtTienThuongThem.setText("");
        cboTienLuong.setSelectedIndex(0);
        txtTongTienLuong.setText("");
    }
    NumberFormat formatter = new DecimalFormat("#.###");

    void fillTable() {
        this.clearImg();
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = dao.selectAll();
            for (NhanVien nv : list) {
                Object[] row
                        = {
                            nv.getMaNV(),
                            //                            nv.getMatKhau(),
                            nv.getHoTen(),
                            nv.isGioiTinh() ? "Nam" : "Nữ",
                            nv.isVaiTro() ? "Quản Lí" : "Nhân viên",
                            nv.getDiaChi(),
                            nv.getsDT(),
                            nv.getEmail(),
                            formatter.format(nv.getLuong()),
                            nv.getHinh(),};
                model.addRow(row);// thêm một hàng vào table
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void clearImg() {
        ImageIcon image = new ImageIcon("logos\\no-image-nv.png");
        Image im = image.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                lblAnh.getHeight(), im.SCALE_SMOOTH));
        lblAnh.setIcon(icon);
    }

    void clearForm() {
        NhanVien nv = new NhanVien();
        this.setFormFirst(nv);
        this.clearImg();
        this.row = -1;
        this.updateStatus();
    }

    void edit() {
        String manv = (String) tblNhanVien.getValueAt(this.row, 0);
        NhanVien nv = dao.selectById(manv);
        this.setForm(nv);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    void setFormFirst(NhanVien nv) {
        txtMaNV.setText(nv.getMaNV());
        txtMatKhau.setText(nv.getMatKhau());
        txtMK2.setText(nv.getMatKhau());
        txtHoTen.setText(nv.getHoTen());
        rdoNam.setSelected(nv.isGioiTinh());
        rdoNu.setSelected(!nv.isGioiTinh());
        rdoQuanLi.setSelected(nv.isVaiTro());
        rdoNhanVien.setSelected(!nv.isVaiTro());
        txtSDT.setText(nv.getsDT());
        txtGmail.setText(nv.getEmail());
        txtLuong.setText(String.valueOf(formatter.format(nv.getLuong())));
        txtDiaChi.setText(nv.getDiaChi());
    }

    void setForm(NhanVien nv) {
        this.setFormFirst(nv);
        if (!nv.getHinh().equals("")) {
            lblAnh.setToolTipText(nv.getHinh());
            ImageIcon image = new ImageIcon("" + XImage.read(nv.getHinh()));
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);
        } else {
            lblAnh.setToolTipText(nv.getHinh());
            ImageIcon image = new ImageIcon("logos\\no-image-nv.png");
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);
        }
    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setMatKhau(txtMatKhau.getText());
        nv.setHoTen(txtHoTen.getText());
        nv.setGioiTinh(rdoNam.isSelected());
        nv.setVaiTro(rdoQuanLi.isSelected());
        nv.setsDT(txtSDT.getText());
        nv.setEmail(txtGmail.getText());
        nv.setLuong(Double.parseDouble(txtLuong.getText().replaceAll(",", "")));
        nv.setDiaChi(txtDiaChi.getText());
        nv.setHinh(lblAnh.getToolTipText());
        return nv;
    }

    void tinhTien() {
        while (true) {
            if (txtSoNgayLamViec.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Số ngày làm việc không được bỏ trống ! ");
                return;
            } else if (!txtSoNgayLamViec.getText().trim().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ngày làm việc phải là số ! ");
                return;
            } else if (Double.parseDouble(txtSoNgayLamViec.getText().trim()) > 31) {
                JOptionPane.showMessageDialog(null, "Số ngày làm việc phải nhỏ hơn 31");
                return;
            } else {
                break;
            }
        }
        double ngay = Double.parseDouble(txtSoNgayLamViec.getText().trim());
        String a = (String) cboTienLuong.getSelectedItem();
        double LuongCB = Double.parseDouble(a.replaceAll(",", ""));
        double TienLuong;

        if (txtTienThuongThem.getText().trim().equals("")) {
            TienLuong = ngay * LuongCB;
        } else {
            while (true) {
                if (!txtTienThuongThem.getText().trim().matches("[0-9]+")) {
                    JOptionPane.showMessageDialog(null, "Tiền thưởng phải là số ! ");
                    return;
                } else if (Double.parseDouble(txtTienThuongThem.getText().trim()) > 500000) {
                    JOptionPane.showMessageDialog(null, "Tiền thưởng phải nhỏ hơn 500.000 ");
                    return;
                } else {
                    break;
                }
            }
            double Thuong = Double.parseDouble(txtTienThuongThem.getText().trim());
            TienLuong = (ngay * LuongCB) + Thuong;
        }
        txtTongTienLuong.setText(formatter.format(TienLuong) + " VNĐ");
    }

    boolean vali_dateTEXT1() {
        if (txtMaNV.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mã nhân viên!");
            txtMaNV.requestFocus();
            return false;
        }
        if (txtMaNV.getText().trim().length() > 7) {
            txtMaNV.requestFocus();
            MsgBox.alert(this, "Mã nhân viên không được quá 7 kí tự!");
            return false;
        }
        if (txtMatKhau.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mật khẩu!");
            txtMatKhau.requestFocus();
            return false;
        }
        if (txtHoTen.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào tên của nhân viên!");
            txtHoTen.requestFocus();
            return false;
        }
        if (txtSDT.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào số điện thoại!");
            txtSDT.requestFocus();
            return false;
        }
        if (txtGmail.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào Email!");
            txtGmail.requestFocus();
            return false;
        }
        if (txtDiaChi.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào Địa Chỉ!");
            txtDiaChi.requestFocus();
            return false;
        }
        if (txtLuong.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào Lương nhân viên!");
            txtLuong.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtLuong.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Lương phải là số!");
            txtLuong.requestFocus();
            return false;
        }
        String email = "\\w+@\\w+(\\.\\w+){1,2}";
        if (txtGmail.getText().matches(email) == false) {
            txtGmail.requestFocus();
            MsgBox.alert(this, "Email sai định dạng!");
            return false;
        }
        String sodienthoai = "0\\d{9,10}";
        if (txtSDT.getText().matches(sodienthoai) == false) {
            txtSDT.requestFocus();
            MsgBox.alert(this, "Số điện thoại sai định dạng!");
            return false;
        }
        String manv = txtMaNV.getText();
        if (dao.selectById(manv) != null) {
            txtMaNV.requestFocus();
            MsgBox.alert(this, "Mã nhân viên này đã tồn tại!");
            return false;
        }
        if (lblAnh.getIcon() == null) {
            MsgBox.alert(this, "Mời bạn chọn ảnh!");
            return false;
        }
        return true;
    }

    boolean vali_dateTEXT2() {
        if (txtMaNV.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mã nhân viên!");
            txtMaNV.requestFocus();
            return false;
        }
        if (txtMaNV.getText().trim().length() > 7) {
            txtMaNV.requestFocus();
            MsgBox.alert(this, "Mã nhân viên không được quá 7 kí tự!");
            return false;
        }
        if (txtMatKhau.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mật khẩu!");
            txtMatKhau.requestFocus();
            return false;
        }
        if (txtHoTen.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào tên của nhân viên!");
            txtHoTen.requestFocus();
            return false;
        }
        if (txtSDT.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào số điện thoại!");
            txtSDT.requestFocus();
            return false;
        }
        if (txtGmail.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào Email!");
            txtGmail.requestFocus();
            return false;
        }
        if (txtDiaChi.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào Địa Chỉ!");
            txtDiaChi.requestFocus();
            return false;
        }
        if (txtLuong.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào Lương nhân viên!");
            txtLuong.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtLuong.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Lương phải là số!");
            txtLuong.requestFocus();
            return false;
        }
        String email = "\\w+@\\w+(\\.\\w+){1,2}";
        if (txtGmail.getText().matches(email) == false) {
            txtGmail.requestFocus();
            MsgBox.alert(this, "Email sai định dạng!");
            return false;
        }
        String sodienthoai = "0\\d{9,10}";
        if (txtSDT.getText().matches(sodienthoai) == false) {
            txtSDT.requestFocus();
            MsgBox.alert(this, "Số điện thoại sai định dạng!");
            return false;
        }
        if (lblAnh.getIcon() == null) {
            MsgBox.alert(this, "Mời bạn chọn ảnh!");
            return false;
        }
        return true;
    }

    void insert() {
        if (vali_dateTEXT1() == true) {
            NhanVien nv = getForm();
            String mk2 = new String(txtMK2.getPassword());
            if (!mk2.equals(nv.getMatKhau())) {
                MsgBox.alert(this, "Mật khẩu không trùng khớp!");
            } else {
                try {
                    dao.insert(nv);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Thêm nhân viên thành công!");
                } catch (Exception e) {
                    System.out.println(e);
//                    MsgBox.alert(this, "Thêm nhân viên thất bại!");
                }
            }
        }
    }

    void update() {
        if (vali_dateTEXT2() == true) {
            NhanVien nv = getForm();
            String mk2 = new String(txtMK2.getPassword());
            if (!mk2.equals(nv.getMatKhau())) {
                MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
            } else {
                try {
                    dao.update(nv);
                    MsgBox.alert(this, "Cập nhật thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Cập nhập thất bại!");
                }
            }
        }
    }

    void delete() {
        if (vali_dateTEXT2() == true) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xóa!");
            } else {
                String manv = txtMaNV.getText();
                if (manv.equals(Auth.user.getMaNV())) {
                    MsgBox.alert(this, "Bạn không được xóa chính bạn!");
                } else if (MsgBox.confirm(this, "Bạn thật sự muốn xóa nhân viên này!")) {
                    try {
                        dao.delete(manv);
                        this.fillTable();
                        this.clearForm();
                        MsgBox.alert(this, "Xóa thành công!");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Xóa thất bại!");
                    }
                }
            }
        }
    }

    void chonAnh() {
        fileChooser = new JFileChooser("logos\\");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file);// lưu hình vào thư mục logos
//            ImageIcon icon = XImage.read(file.getName());// đọc hình từ logos

            ImageIcon image = new ImageIcon("" + XImage.read(file.getName()));
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);

//            lblHinh.setIcon(icon);
            lblAnh.setToolTipText(file.getName());// giữ tên hình trong tooltip
        }
    }

    void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiem.getText();
            List<NhanVien> list = dao.selectByKeyword(keyword);
            for (NhanVien nv : list) {
                Object[] row
                        = {
                            nv.getMaNV(),
                            nv.getMatKhau(),
                            nv.getHoTen(),
                            nv.isGioiTinh() ? "Nam" : "Nữ",
                            nv.isVaiTro() ? "Quản Lí" : "Nhân viên",
                            nv.getDiaChi(),
                            nv.getsDT(),
                            nv.getEmail(),
                            nv.getLuong(),
                            nv.getHinh(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void Last() {
        this.row = tblNhanVien.getRowCount() - 1;
        this.edit();
    }

    void Next() {
        if (this.row < tblNhanVien.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void First() {
        this.row = 0;
        this.edit();
    }

    void Prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblNhanVien.getRowCount() - 1);
        txtMaNV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }
}
