/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.IT_Coffee.UI;

import Com.IT_Coffee.utils.MsgBox;
import Com.IT_Coffee.utils.XImage;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dang
 */
public class QuenMKDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form QuenMKDiaLog
     */
    String username = "dangletv234@gmail.com";
    String password = "dang91120011";
    String tkemail;

    public QuenMKDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Quên mật khẩu");
        setLocationRelativeTo(null);
        Panldemo.setBackground(new Color(0, 0, 0, 60));
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panldemo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnTroVe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhập vào tài khoản của bạn");

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnTroVe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTroVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/Log out.png"))); // NOI18N
        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanldemoLayout = new javax.swing.GroupLayout(Panldemo);
        Panldemo.setLayout(PanldemoLayout);
        PanldemoLayout.setHorizontalGroup(
            PanldemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanldemoLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(PanldemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanldemoLayout.createSequentialGroup()
                        .addComponent(btnTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanldemoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        PanldemoLayout.setVerticalGroup(
            PanldemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanldemoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(PanldemoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnTroVe))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(Panldemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/Cooffee_QuenMK.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        this.TimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        this.troVe();
    }//GEN-LAST:event_btnTroVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMKDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMKDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMKDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMKDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMKDiaLog dialog = new QuenMKDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    void TimKiem() {
        if (vali_datee() == true) {
            String username = txtTaiKhoan.getText();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=IT_Coffee";
                Connection con = DriverManager.getConnection(url, "sa", "123");
                PreparedStatement ps = con.prepareStatement("select Email from NhanVien where MaNV = '" + username + "'");
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    tkemail = rs.getString(1);
                    //txtcauhoibaomat.setText(rs.getString(1));
                    //MsgBox.confirm(this, "chúng tối sẽ gửi mật khẩu đến Email \n" + rs.getString(1));
                    int tam = JOptionPane.showConfirmDialog(this, "Chúng tối sẽ gửi một mật khẩu đến Gmail\n" + rs.getString(1) + "?", "xác Nhận",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE);
                    if (tam == JOptionPane.YES_NO_OPTION) {
                        this.Email();
                    }

                } else {
                    MsgBox.alert(this, "Tài khoản này không tồn tại!");
                    con.close();
                    rs.close();
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    boolean vali_datee() {
        if (txtTaiKhoan.getText().trim().length() == 0) {
            txtTaiKhoan.requestFocus();
            MsgBox.alert(this, "mời bạn nhập tài khoản của bạn");
            return false;
        }
        return true;
    }

    void Email() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=IT_Coffee";
            Connection con = DriverManager.getConnection(url, "sa", "123");
            PreparedStatement ps = con.prepareStatement("select MatKhau from NhanVien where MaNV = '" + txtTaiKhoan.getText() + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String mk = rs.getString(1);
                Properties prop = new Properties();
                prop.put("mail.smtp.host", "smtp.gmail.com");
                prop.put("mail.smtp.port", "587");
                prop.put("mail.smtp.auth", "true");
                prop.put("mail.smtp.starttls.enable", "true"); //TLS
                // đăng nhập email
                Session session = Session.getInstance(prop,
                        new javax.mail.Authenticator() {
                            protected PasswordAuthentication getPasswordAuthentication() {
                                return new PasswordAuthentication(username, password);
                            }
                        });

                try {
                    javax.mail.Message message = new MimeMessage(session);
                    message.setFrom(new InternetAddress("dangletv234@gmail.com"));
                    message.setRecipients(
                            javax.mail.Message.RecipientType.TO,
                            InternetAddress.parse(tkemail)
                    );
                    message.setSubject("Lấy lại mật khẩu");
                    message.setText("mật khẩu tài khoản của bạn là:" + mk);

                    Transport.send(message);
                    JOptionPane.showMessageDialog(this, "Mật khẩu của bạn đã được gửi về Email của bạn!");
                    System.out.println("Done");

                } catch (MessagingException e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            //------
        }
    }

    void troVe() {
        this.dispose();
        DangNhapDiaLog dialog = new DangNhapDiaLog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (MsgBox.confirm(null, "Bạn muốn thoát khỏi chương trình?")) {
                    System.exit(0);
                }
            }
        });
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panldemo;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
