/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Com.IT_Coffee.UI;

import Com.IT_Coffee.DAO.LoaiSPDAO;
import Com.IT_Coffee.DAO.SanPhamDAO;
import Com.IT_Coffee.Entity.LoaiSP;
import Com.IT_Coffee.Entity.NhanVien;
import Com.IT_Coffee.Entity.SanPham;
import Com.IT_Coffee.utils.Auth;
import Com.IT_Coffee.utils.MsgBox;
import Com.IT_Coffee.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author HMD
 */
public class SanPhamDialog extends javax.swing.JDialog {

    /**
     * Creates new form SanPhamDialog
     */
    public SanPhamDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblAnh = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnFirst1 = new javax.swing.JButton();
        btnPrev1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnLast1 = new javax.swing.JButton();
        cboHienThiSP = new javax.swing.JCheckBox();
        txtDonGia = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnLamMoi1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboLoaiSP = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnXuatFileEXCEL = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaLoaiSP = new javax.swing.JTextField();
        txtTenLoaiSP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnThem2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        btnLamMoi2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnFirst2 = new javax.swing.JButton();
        btnPrev2 = new javax.swing.JButton();
        btnNext2 = new javax.swing.JButton();
        btnLast2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiSP = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiemLSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel6.setLayout(null);

        tblSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Size", "Đơn giá", "Hình"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(90, 480, 1020, 220);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAnh.setText(" ");
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFirst1.setBackground(new java.awt.Color(102, 102, 255));
        btnFirst1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFirst1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/first24.png"))); // NOI18N
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });

        btnPrev1.setBackground(new java.awt.Color(102, 102, 255));
        btnPrev1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrev1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/prev24.png"))); // NOI18N
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });

        btnNext1.setBackground(new java.awt.Color(102, 102, 255));
        btnNext1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/next24.png"))); // NOI18N
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        btnLast1.setBackground(new java.awt.Color(102, 102, 255));
        btnLast1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLast1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/last24.png"))); // NOI18N
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });

        cboHienThiSP.setBackground(new java.awt.Color(255, 255, 255));
        cboHienThiSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboHienThiSP.setText("Hiển thị tất cả sản phẩm");
        cboHienThiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboHienThiSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnFirst1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(btnPrev1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(btnNext1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(btnLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(cboHienThiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnLast1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext1)
                            .addComponent(btnPrev1)
                            .addComponent(btnFirst1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(cboHienThiSP)))
                .addContainerGap())
        );

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThem1.setBackground(new java.awt.Color(0, 255, 102));
        btnThem1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/them24.png"))); // NOI18N
        btnThem1.setText("     Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(0, 255, 102));
        btnXoa1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/xoa24.png"))); // NOI18N
        btnXoa1.setText("       Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(0, 255, 102));
        btnSua1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/sua24.png"))); // NOI18N
        btnSua1.setText("      Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnLamMoi1.setBackground(new java.awt.Color(0, 255, 102));
        btnLamMoi1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/moi24.png"))); // NOI18N
        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnThem1)
                .addGap(18, 18, 18)
                .addComponent(btnXoa1)
                .addGap(21, 21, 21)
                .addComponent(btnSua1)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Đơn giá :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Size :");

        cboSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhỏ", "Vừa", "Lớn" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Tên sản phẩm :");

        txtTenSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Mã sản phẩm :");

        txtMaSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Loại SP :");

        cboLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Tìm Kiếm Sản Phẩm");

        txtTimKiem.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        btnXuatFileEXCEL.setBackground(new java.awt.Color(255, 153, 51));
        btnXuatFileEXCEL.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnXuatFileEXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/excel24.png"))); // NOI18N
        btnXuatFileEXCEL.setText("Xuất danh sách");
        btnXuatFileEXCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileEXCELActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatFileEXCEL))
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(17, 17, 17))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cboLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatFileEXCEL))
                .addGap(12, 12, 12))
        );

        jPanel6.add(jPanel4);
        jPanel4.setBounds(90, 10, 1010, 460);

        jTabbedPane1.addTab("Sản Phẩm", jPanel6);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên loại sản phẩm :");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã loại sản phẩm :");

        txtMaLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTenLoaiSP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThem2.setBackground(new java.awt.Color(0, 255, 102));
        btnThem2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/them24.png"))); // NOI18N
        btnThem2.setText("     Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnXoa2.setBackground(new java.awt.Color(0, 255, 102));
        btnXoa2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/xoa24.png"))); // NOI18N
        btnXoa2.setText("       Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        btnSua2.setBackground(new java.awt.Color(0, 255, 102));
        btnSua2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/sua24.png"))); // NOI18N
        btnSua2.setText("      Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        btnLamMoi2.setBackground(new java.awt.Color(0, 255, 102));
        btnLamMoi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamMoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/moi24.png"))); // NOI18N
        btnLamMoi2.setText("Làm mới");
        btnLamMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem2)
                .addGap(18, 18, 18)
                .addComponent(btnXoa2)
                .addGap(18, 18, 18)
                .addComponent(btnSua2)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFirst2.setBackground(new java.awt.Color(102, 102, 255));
        btnFirst2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFirst2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/first24.png"))); // NOI18N
        btnFirst2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst2ActionPerformed(evt);
            }
        });

        btnPrev2.setBackground(new java.awt.Color(102, 102, 255));
        btnPrev2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrev2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/prev24.png"))); // NOI18N
        btnPrev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev2ActionPerformed(evt);
            }
        });

        btnNext2.setBackground(new java.awt.Color(102, 102, 255));
        btnNext2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/next24.png"))); // NOI18N
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        btnLast2.setBackground(new java.awt.Color(102, 102, 255));
        btnLast2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLast2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/iicon/last24.png"))); // NOI18N
        btnLast2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnPrev2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnLast2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLast2)
                    .addComponent(btnNext2)
                    .addComponent(btnPrev2)
                    .addComponent(btnFirst2))
                .addContainerGap())
        );

        tblLoaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại SP", "Tên loại SP"
            }
        ));
        tblLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLoaiSP);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tìm Kiếm Loại SP:");

        txtTimKiemLSP.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtTimKiemLSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemLSPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaLoaiSP)
                            .addComponent(txtTenLoaiSP)
                            .addComponent(txtTimKiemLSP))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(txtTimKiemLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loại Sản Phẩm", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 790));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Com/icon/backgrouppp.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiSPMouseClicked
        if (evt.getClickCount() == 2) {
            this.row2 = tblLoaiSP.getSelectedRow();
            this.edit2();
        } else {
            this.row2 = tblLoaiSP.getSelectedRow();
            this.edit2();
        }
    }//GEN-LAST:event_tblLoaiSPMouseClicked

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        this.insert2();
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        this.delete2();
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        this.update2();
    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnLamMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi2ActionPerformed
        this.clearForm2();
    }//GEN-LAST:event_btnLamMoi2ActionPerformed

    private void btnFirst2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst2ActionPerformed
        this.first2();
    }//GEN-LAST:event_btnFirst2ActionPerformed

    private void btnPrev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev2ActionPerformed
        this.prev2();
    }//GEN-LAST:event_btnPrev2ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        this.next2();
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnLast2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast2ActionPerformed
        this.last2();
    }//GEN-LAST:event_btnLast2ActionPerformed

    private void cboLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSPActionPerformed
        this.fillTable1();
    }//GEN-LAST:event_cboLoaiSPActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        this.insert1();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        this.delete1();
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        this.update1();
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        this.clearForm1();
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        this.first1();
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        this.prev1();
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        this.next1();
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        this.last1();
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        if (evt.getClickCount() == 2) {
            this.row1 = tblSanPham.getSelectedRow();
            this.edit1();
        } else {
            this.row1 = tblSanPham.getSelectedRow();
            this.edit1();
        }
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
        this.chonAnh();
    }//GEN-LAST:event_lblAnhMouseClicked

    private void cboHienThiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboHienThiSPActionPerformed
        this.fillTable1();
        this.updateStatus1();
    }//GEN-LAST:event_cboHienThiSPActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        this.timKiem();
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtTimKiemLSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemLSPKeyReleased
        // TODO add your handling code here:
        this.timKiem2();
    }//GEN-LAST:event_txtTimKiemLSPKeyReleased

    private void btnXuatFileEXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileEXCELActionPerformed
        // TODO add your handling code here:
        this.xuatFileExcel();
    }//GEN-LAST:event_btnXuatFileEXCELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPhamDialog dialog = new SanPhamDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnFirst2;
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnLamMoi2;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnLast2;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnPrev1;
    private javax.swing.JButton btnPrev2;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JButton btnXuatFileEXCEL;
    private javax.swing.JCheckBox cboHienThiSP;
    private javax.swing.JComboBox cboLoaiSP;
    private javax.swing.JComboBox cboSize;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JTable tblLoaiSP;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaLoaiSP;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTenLoaiSP;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiemLSP;
    // End of variables declaration//GEN-END:variables

    SanPhamDAO dao1 = new SanPhamDAO();
    int row1 = -1;
    LoaiSPDAO dao2 = new LoaiSPDAO();
    int row2 = -1;

    private void init() {
        this.setTitle("QUẢN LÝ SẢN PHẨM");
        this.setLocationRelativeTo(null);

        tblSanPham.setDefaultEditor(Object.class, null);
        tblLoaiSP.setDefaultEditor(Object.class, null);

        this.clearImg(); //đặt ảnh về mặc định

        this.fillComboBoxLoaiSP(); //fillCombox and fillTable
        this.fillTable2();

        jPanel6.setBackground(new Color(0, 0, 0, 100));
        jPanel2.setBackground(new Color(0, 0, 0, 100));

        System.out.println(cboSize.getSelectedItem().toString());
    }

    void fillComboBoxLoaiSP() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiSP.getModel();
        model.removeAllElements();
        List<LoaiSP> list = dao2.selectAll();
        for (LoaiSP lsp : list) {
            model.addElement(lsp);
        }
        this.fillTable1();
    }
    NumberFormat formatter = new DecimalFormat("#.###");

    void fillTable1() {
        this.clearImg();
        this.updateStatus1();
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        LoaiSP lsp = (LoaiSP) cboLoaiSP.getSelectedItem();
        // Hiện thị all sp khi chọn check box
        if (cboHienThiSP.isSelected()) {
            List<SanPham> list = dao1.selectAll();
            for (SanPham sp : list) {
                String tenlsp = dao2.selectById(sp.getLoaiSP()).getTenLoaiSP();
                model.addRow(new Object[]{
                    sp.getMaSP(), sp.getTenSP(), tenlsp, sp.getSize(),
                    formatter.format(sp.getDonGia()), sp.getHinh()
                });
            }
        } else if (lsp != null) {
            List<SanPham> list = dao1.selectByLoaiSP(lsp.getMaLoaiSP());
            for (SanPham sp : list) {
                String tenlsp = dao2.selectById(sp.getLoaiSP()).getTenLoaiSP();
                model.addRow(new Object[]{
                    sp.getMaSP(), sp.getTenSP(), tenlsp, sp.getSize(),
                    formatter.format(sp.getDonGia()), sp.getHinh()
                });
            }
        }
    }

    void edit1() {
        tblSanPham.setRowSelectionInterval(this.row1, this.row1);
        String masp = (String) tblSanPham.getValueAt(this.row1, 0);
        SanPham sp = dao1.selectById(masp);
        this.setForm1(sp);
        this.updateStatus1();
    }

    void setForm1(SanPham sp) {
        txtMaSP.setText(sp.getMaSP());
        txtTenSP.setText(sp.getTenSP());
        cboSize.setSelectedItem(sp.getSize());
        txtDonGia.setText(String.valueOf(formatter.format(sp.getDonGia())));
        if (!sp.getHinh().equals("")) {
            lblAnh.setToolTipText(sp.getHinh());
            ImageIcon image = new ImageIcon("" + XImage.read(sp.getHinh()));
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);
        } else {
            lblAnh.setToolTipText(sp.getHinh());
            ImageIcon image = new ImageIcon("logos\\no-image-sp.png");
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);
        }
    }

    SanPham getForm1() {
        LoaiSP lsp = (LoaiSP) cboLoaiSP.getSelectedItem();
        SanPham sp = new SanPham();
        sp.setLoaiSP(lsp.getMaLoaiSP());
        sp.setMaSP(txtMaSP.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setSize(cboSize.getSelectedItem().toString());
        sp.setDonGia(Double.parseDouble(txtDonGia.getText()));
        sp.setHinh(lblAnh.getToolTipText());
        return sp;
    }

    boolean validate_data1() {
        if (txtMaSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mã sản phẩm!");
            txtMaSP.requestFocus();
            return false;
        }
        if (txtMaSP.getText().trim().length() > 7) {
            MsgBox.alert(this, "Mã sản phẩm không được quá 7 kí tự!");
            txtMaSP.requestFocus();
            return false;
        }
        if (txtTenSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào tên sản phẩm!");
            txtTenSP.requestFocus();
            return false;
        }
        if (txtDonGia.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào đơn giá cho sản phẩm");
            txtDonGia.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtDonGia.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Đơn giá của sản phẩm phải là số thực");
            txtDonGia.requestFocus();
            return false;
        }
        String masp = txtMaSP.getText();
        if (dao1.selectById(masp) != null) {
            MsgBox.alert(this, "Má sản Phẩm này đã tồn tại!");
            return false;
        }
        return true;
    }

    boolean validate_data11() {
        if (txtMaSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mã sản phẩm!");
            txtMaSP.requestFocus();
            return false;
        }
        if (txtMaSP.getText().trim().length() > 7) {
            MsgBox.alert(this, "Mã sản phẩm không được quá 7 kí tự!");
            txtMaSP.requestFocus();
            return false;
        }
        if (txtTenSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào tên sản phẩm!");
            txtTenSP.requestFocus();
            return false;
        }
        if (txtDonGia.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào đơn giá cho sản phẩm");
            txtDonGia.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtDonGia.getText());
        } catch (Exception e) {
            MsgBox.alert(this, "Đơn giá của sản phẩm phải là số thực");
            txtDonGia.requestFocus();
            return false;
        }
        return true;
    }

    void clearImg() {
        ImageIcon image = new ImageIcon("logos\\no-image-sp.png");
        Image im = image.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                lblAnh.getHeight(), im.SCALE_SMOOTH));
        lblAnh.setIcon(icon);
    }

    void clearForm1() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        cboSize.setSelectedIndex(0);
        txtDonGia.setText("");
        this.row1 = -1;
        this.clearImg();
        this.updateStatus1();
    }

    void insert1() {
        if (validate_data1()) {
            SanPham sp = getForm1();
            try {
                dao1.insert(sp);
                this.fillTable1();
                this.clearForm1();
                MsgBox.alert(this, "Thêm sản phẩm thành công");
            } catch (Exception e) {
//                System.out.println(e);
                MsgBox.alert(this, "Thêm sản phẩm thất bại");
            }
        }
    }

    void update1() {
        if (validate_data11()) {
            SanPham sp = getForm1();
            try {
                dao1.update(sp);
                this.fillTable1();
                this.clearForm1();
                MsgBox.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại");
            }
        }
    }

    void delete1() {
        if (validate_data11()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xóa sản phẩm!");
            } else {
                if (MsgBox.confirm(this, "Bạn thực sự muốn xóa sản phẩm này!")) {
                    String masp = txtMaSP.getText();
                    try {
                        dao1.delete(masp);
                        this.fillTable1();
                        this.clearForm1();
                        MsgBox.alert(this, "Xóa thành công");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Xóa thất bại");
                    }
                }
            }
        }
    }

    void first1() {
        this.row1 = 0;
        this.edit1();
    }

    void prev1() {
        if (this.row1 > 0) {
            this.row1--;
            this.edit1();
        }
    }

    void next1() {
        if (this.row1 < tblSanPham.getRowCount() - 1) {
            this.row1++;
            this.edit1();
        }
    }

    void last1() {
        this.row1 = tblSanPham.getRowCount() - 1;
        this.edit1();
    }

    void updateStatus1() {
        boolean edit = (this.row1 >= 0);
        boolean first = (this.row1 == 0);
        boolean last = (this.row1 == tblSanPham.getRowCount() - 1);
        //trường hợp check xem all sp k cho thực hiện thêm xóa sửa mới và chọn lsp
        boolean allSP = (cboHienThiSP.isSelected());
        cboLoaiSP.setEnabled(!allSP);
        txtMaSP.setEditable(!edit && !allSP);
        //fix lại 3 nút thêm xóa sửa và thêm nút thêm mới
        btnThem1.setEnabled(!edit && !allSP);
        btnSua1.setEnabled(edit && !allSP);
        btnXoa1.setEnabled(edit && !allSP);
        btnLamMoi1.setEnabled(!allSP);
        //fix all form (các txt cbo còn lại) khi chọn xem all sp
        txtTenSP.setEditable(!allSP);
        cboSize.setEnabled(!allSP);
        txtDonGia.setEditable(!allSP);

        btnFirst1.setEnabled(edit && !first);
        btnPrev1.setEnabled(edit && !first);
        btnNext1.setEnabled(edit && !last);
        btnLast1.setEnabled(edit && !last);

        // Không phải quản lý thì không được update
//        if (!Auth.isManager()) {
//            btnThem1.setEnabled(false);
//            btnXoa1.setEnabled(false);
//            btnSua1.setEnabled(false);
//            btnLamMoi1.setEnabled(false);
//
//            btnThem2.setEnabled(false);
//            btnXoa2.setEnabled(false);
//            btnSua2.setEnabled(false);
//            btnLamMoi2.setEnabled(false);
//        }
    }

    void chonAnh() {
        fileChooser = new JFileChooser("logos\\");
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file);// lưu hình vào thư mục logos
//            ImageIcon icon = XImage.read(file.getName());// đọc hình từ logos

            ImageIcon image = new ImageIcon("" + XImage.read(file.getName()));
            Image im = image.getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnh.getWidth(),
                    lblAnh.getHeight(), im.SCALE_SMOOTH));
            lblAnh.setIcon(icon);

//            lblHinh.setIcon(icon);
            lblAnh.setToolTipText(file.getName());// giữ tên hình trong tooltip
        }
    }

    void fillTable2() {
        this.updateStatus2();
        DefaultTableModel model = (DefaultTableModel) tblLoaiSP.getModel();
        model.setRowCount(0);
        try {
            List<LoaiSP> list = dao2.selectAll();
            for (LoaiSP lsp : list) {
                Object[] row = {
                    lsp.getMaLoaiSP(),
                    lsp.getTenLoaiSP()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void edit2() {
        tblLoaiSP.setRowSelectionInterval(this.row2, this.row2);
        String malsp = (String) tblLoaiSP.getValueAt(this.row2, 0);
        LoaiSP lsp = dao2.selectById(malsp);
        this.setForm2(lsp);
        this.updateStatus2();
    }

    void setForm2(LoaiSP lsp) {
        txtMaLoaiSP.setText(lsp.getMaLoaiSP());
        txtTenLoaiSP.setText(lsp.getTenLoaiSP());
    }

    LoaiSP getForm2() {
        LoaiSP lsp = new LoaiSP();
        lsp.setMaLoaiSP(txtMaLoaiSP.getText());
        lsp.setTenLoaiSP(txtTenLoaiSP.getText());
        return lsp;
    }

    boolean validate_data2() {
        if (txtMaLoaiSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mã loại sản phẩm!");
            txtMaLoaiSP.requestFocus();
            return false;
        }
        if (txtMaLoaiSP.getText().trim().length() > 7) {
            txtMaLoaiSP.requestFocus();
            MsgBox.alert(this, "Mã loại sản phẩm không được quá 7 kí tự!");
            return false;
        }
        if (txtTenLoaiSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào tên loại sản phẩm!");
            txtTenLoaiSP.requestFocus();
            return false;
        }
        String malsp = txtMaLoaiSP.getText();
        if (dao2.selectById(malsp) != null) {
            MsgBox.alert(this, "Má Loại SP này đã tồn tại!");
            return false;
        }
        return true;
    }

    boolean validate_data22() {
        if (txtMaLoaiSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào mã loại sản phẩm!");
            txtMaLoaiSP.requestFocus();
            return false;
        }
        if (txtMaLoaiSP.getText().trim().length() > 7) {
            txtMaLoaiSP.requestFocus();
            MsgBox.alert(this, "Mã loại sản phẩm không được quá 7 kí tự!");
            return false;
        }
        if (txtTenLoaiSP.getText().trim().length() == 0) {
            MsgBox.alert(this, "Mời bạn nhập vào tên loại sản phẩm!");
            txtTenLoaiSP.requestFocus();
            return false;
        }
        return true;
    }

    void clearForm2() {
        LoaiSP lsp = new LoaiSP();
        this.setForm2(lsp);
        this.row2 = -1;
        this.fillTable2();
        this.updateStatus2();
    }

    void insert2() {
        if (validate_data2()) {
            LoaiSP lsp = getForm2();
            try {
                dao2.insert(lsp);
                this.fillTable2();
                this.clearForm2();
                this.fillComboBoxLoaiSP();
                MsgBox.alert(this, "Thêm loại sản phẩm thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm loại sản phẩm thất bại");
            }
        }
    }

    void update2() {
        if (validate_data22()) {
            LoaiSP lsp = getForm2();
            try {
                dao2.update(lsp);
                this.fillTable2();
                this.clearForm2();
                this.fillComboBoxLoaiSP();
                MsgBox.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                MsgBox.alert(this, "Cập nhật thất bại");
            }
        }
    }

    void delete2() {
        if (validate_data22()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xóa loại SP này!");
            } else {
                if (MsgBox.confirm(this, "Bạn thật sự muốn xóa loại SP này!")) {
                    String malsp = txtMaLoaiSP.getText();
                    try {
                        dao2.delete(malsp);
                        this.fillTable2();
                        this.clearForm2();
                        this.fillComboBoxLoaiSP();
                        MsgBox.alert(this, "Xóa thành công");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Xóa thất bại");
                    }
                }
            }
        }
    }

    void first2() {
        this.row2 = 0;
        this.edit2();
    }

    void prev2() {
        if (this.row2 > 0) {
            this.row2--;
            this.edit2();
        }
    }

    void next2() {
        if (this.row2 < tblLoaiSP.getRowCount() - 1) {
            this.row2++;
            this.edit2();
        }
    }

    void last2() {
        this.row2 = tblLoaiSP.getRowCount() - 1;
        this.edit2();
    }

    private void updateStatus2() {
        boolean edit = (this.row2 >= 0);
        boolean first = (this.row2 == 0);
        boolean last = (this.row2 == tblLoaiSP.getRowCount() - 1);
        txtMaLoaiSP.setEditable(!edit);
        btnThem2.setEnabled(!edit);
        btnSua2.setEnabled(edit);
        btnXoa2.setEnabled(edit);
        btnFirst2.setEnabled(edit && !first);
        btnPrev2.setEnabled(edit && !first);
        btnNext2.setEnabled(edit && !last);
        btnLast2.setEnabled(edit && !last);
    }

    void timKiem() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiem.getText();
            List<SanPham> list = dao1.selectByKeyWord(keyword);
            for (SanPham sp : list) {
                Object[] row
                        = {
                            sp.getMaSP(),
                            sp.getTenSP(),
                            sp.getLoaiSP(),
                            sp.getSize(),
                            sp.getDonGia(),
                            sp.getHinh()
                        };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void timKiem2() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiSP.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiemLSP.getText();
            List<LoaiSP> list = dao2.selectByKeyword2(keyword);
            for (LoaiSP sp : list) {
                Object[] row
                        = {
                            sp.getMaLoaiSP(),
                            sp.getTenLoaiSP(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void xuatFileExcel() {
//        TableModel model = tblSanPham.getModel();
//        JFileChooser excelExportChooser = new JFileChooser();
//        excelExportChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
//        excelExportChooser.setDialogTitle("Save Excel File");
//        //filter the file
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", "*.xls", "xls", "xlsx", "xlsn");
//        excelExportChooser.addChoosableFileFilter(filter);
//        excelExportChooser.setFileFilter(filter);
//        int excelchooser = excelExportChooser.showSaveDialog(null);
//        if (excelchooser == JFileChooser.APPROVE_OPTION) {
//            Workbook workbook = new XSSFWorkbook();
//            Sheet sheet = workbook.createSheet("SalesReturnsDetails");
//            Row row;
//            Cell cell;
//            try {
//                // write the column headers
//                row = sheet.createRow(0);
//                for (int j = 0; j < model.getColumnCount(); j++) {
//                    cell = row.createCell(j);
//                    cell.setCellValue(model.getColumnName(j));
//                }
//                for (int i = 0; i < model.getRowCount(); i++) {
//                    row = sheet.createRow(i + 1);
//                    for (int j = 0; j < model.getColumnCount(); j++) {
//                        cell = row.createCell(j);
//                        cell.setCellValue(model.getValueAt(i, j).toString());
//                    }
//                }
//            } catch (Exception e) {
//                //JOptionPane.showMessageDialog(null, "xuất file thành công");
//            }
//            FileOutputStream excelFIS;
//            try {
//                excelFIS = new FileOutputStream(excelExportChooser.getSelectedFile() + ".xlsx");
//                workbook.write(excelFIS);
//                workbook.close();
//                MsgBox.alert(this, "Xuât File thành công!");
//            } catch (FileNotFoundException ex) {
//                System.out.println(ex);
//            } catch (IOException ex) {
//                System.out.println(ex);
//            }
//        }

        JFileChooser excelExportChooser = new JFileChooser();
        excelExportChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        excelExportChooser.setDialogTitle("Save Excel File");
        //filter the file
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", "*.xls", "xls", "xlsx", "xlsn");
        excelExportChooser.addChoosableFileFilter(filter);
        excelExportChooser.setFileFilter(filter);
        int excelchooser = excelExportChooser.showSaveDialog(null);
        if (excelchooser == JFileChooser.APPROVE_OPTION) {
            try {
                LoaiSP lsp = (LoaiSP) cboLoaiSP.getSelectedItem();
                List<SanPham> list = null;
                String nameSheet = "";
                // Hiện thị all sp khi chọn check box
                if (cboHienThiSP.isSelected()) {
                    list = dao1.selectAll();
                    nameSheet = "Tất cả sản phẩm";
                } else if (lsp != null) {
                    list = dao1.selectByLoaiSP(lsp.getMaLoaiSP());
                    nameSheet = lsp.getTenLoaiSP();
                }

                XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet sheet = workbook.createSheet(nameSheet);
                XSSFRow row = null;
                Cell cell = null;

                //meger title
                sheet.addMergedRegion(new CellRangeAddress(0, 1, 0, 5));

                //create CellStyle
                CellStyle cellStyle = createStyleForHeader(sheet);
                CellStyle cellStyle2 = createStyleForTittle(sheet);

                row = sheet.createRow(0);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellStyle(cellStyle2);
                cell.setCellValue("DANH SÁCH SẢN PHẨM");

                //create column headings
                row = sheet.createRow(2);
                cell = row.createCell(0, CellType.STRING);
                cell.setCellStyle(cellStyle);
                cell.setCellValue(" MÃ SP ");

                cell = row.createCell(1, CellType.STRING);
                cell.setCellStyle(cellStyle);
                cell.setCellValue(" TÊN SP                            ");

                cell = row.createCell(2, CellType.NUMERIC);
                cell.setCellStyle(cellStyle);
                cell.setCellValue(" LOẠI SP                           ");

                cell = row.createCell(3, CellType.STRING);
                cell.setCellStyle(cellStyle);
                cell.setCellValue(" SIZE          ");

                cell = row.createCell(4, CellType.STRING);
                cell.setCellStyle(cellStyle);
                cell.setCellValue(" ĐƠN GIÁ       ");

                cell = row.createCell(5, CellType.STRING);
                cell.setCellStyle(cellStyle);
                cell.setCellValue(" HÌNH                   ");

                //Auto resize column width
                int numberOfColumn = sheet.getRow(2).getPhysicalNumberOfCells();
                autosizeColumn(sheet, numberOfColumn);

                if (list != null) {
                    int i = -1;
                    for (SanPham excel : list) {
                        String tenlsp = dao2.selectById(excel.getLoaiSP()).getTenLoaiSP();
                        i++;
                        row = sheet.createRow(3 + i);

                        cell = row.createCell(0);
                        cell.setCellValue(excel.getMaSP());

                        cell = row.createCell(1);
                        cell.setCellValue(excel.getTenSP());

                        cell = row.createCell(2);
                        cell.setCellValue(tenlsp);

                        cell = row.createCell(3);
                        cell.setCellValue(excel.getSize());

                        cell = row.createCell(4);
                        cell.setCellValue(excel.getDonGia());

                        cell = row.createCell(5);
                        cell.setCellValue(excel.getHinh());
                    }
                }

                FileOutputStream excelFIS;
                excelFIS = new FileOutputStream(excelExportChooser.getSelectedFile() + ".xlsx");
                workbook.write(excelFIS);
                workbook.close();
                MsgBox.alert(this, "Xuất file thành công!");

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    void autosizeColumn(Sheet sheet, int lastColumn) {
        for (int columnIndex = 0; columnIndex < lastColumn; columnIndex++) {
            sheet.autoSizeColumn(columnIndex);
        }
    }

    private static CellStyle createStyleForHeader(Sheet sheet) {
        // Create font
        Font font = sheet.getWorkbook().createFont();
        font.setFontName("Calibri");
        font.setBold(true);
        font.setFontHeightInPoints((short) 12); // font size
        font.setColor(IndexedColors.WHITE.getIndex()); // text color

        // Create CellStyle
        CellStyle cellStyle = sheet.getWorkbook().createCellStyle();
        cellStyle.setFont(font);
        cellStyle.setFillForegroundColor(IndexedColors.GREEN.getIndex());
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        return cellStyle;
    }

    private static CellStyle createStyleForTittle(Sheet sheet) {
        // Create font
        Font font = sheet.getWorkbook().createFont();
        font.setFontName("Calibri");
        font.setBold(true);
        font.setFontHeightInPoints((short) 20); // font size
        font.setColor(IndexedColors.BLACK.getIndex()); // text color

        // Create CellStyle
        CellStyle cellStyle = sheet.getWorkbook().createCellStyle();
        cellStyle.setFont(font);
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        cellStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        return cellStyle;
    }

}
